kafka:
  bootstrap-servers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9093

spring:
  kafka:
    bootstrap-servers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9093
    properties:
      ssl:
        truststore:
          location: /tmp/certs/truststore.p12
